### ISSUE TITLE
[An error occurred in the loading package versions (package:MyPackage)] Unexpected end of JSON input

### ISSUE THREAD

**Issue by LynxWall** [aliasadidev/vscode-npm-gui#26]
Packages are hosted in ProGet package Server.
App shows loaded versions and can search for packages in ProGet. However, attempting to run Load Package Versions throws this error.

**Comment by LynxWall** [comment]
Figured out the issue. Needed to use the flatfile URL, which returned correct version information.
Their search URL also ends with /search instead of the common /query.

**Comment by aliasadidev** [comment]
I think your problem is same as #15, this extension only support NuGet standard JSON result.  
To see your API result follow the below steps:
VSCode -> Menu -> Help -> Toggle Developer Tools > Console Tab

*compare it with NuGet result [https://azuresearch-usnc.nuget.org/query](https://azuresearch-usnc.nuget.org/query)

[check out  settings.json too](https://github.com/aliasadidev/vscode-npm-gui#you-can-override-the-following-settings-in-the-user-or-workspace-settingsjson)
