### ISSUE TITLE
Adding new package from ProGet hangs when getting package details

### ISSUE THREAD

**Issue by LynxWall** [aliasadidev/vscode-npm-gui#37]
Prior to the 2.x upgrade this was working fine with ProGet. However, after the upgrade I am not able to add new packages.
I am able to manage installed packages and the package links work.

The package manager is able to find packages, but then just hangs with an overlay that never goes away when attempting to get the package information. Following screenshot shows what I'm seeing:
![image](https://user-images.githubusercontent.com/5261586/160637212-c1379179-ba97-41dc-9fa0-20e034ff5f19.png)

**Comment by aliasadidev** [comment]
ProGet returns `string` datatype instead of  `array` for authors property 
![image](https://user-images.githubusercontent.com/6399165/163809308-3bc36aec-616a-4902-9577-a465b25f5087.png)

the property name is a plural noun `authors` but the value of it is a string! :)
the other sources return an array
**I fixed it**

**Comment by aliasadidev** [comment]
you can test it in version 2.0.2

**Comment by LynxWall** [comment]
Verified that Nuget Package Manager is working with ProGet now. Was able to successfully list and view packages from ProGet.
Thanks!
