### ISSUE TITLE
wrong last stable version

### ISSUE THREAD

**Issue by askovpen** [aliasadidev/vscode-npm-gui#75]
for package [SqlKata](https://www.nuget.org/packages/SqlKata/) npm-gui show latest stable version 3.2.3, but last stable 2.4.0

**Comment by aliasadidev** [comment]
Hi @askovpen 

It appears that the issue you're experiencing is related to a potential cache inconsistency on the NuGet.org platform. It seems that a newer version of the package was uploaded, but subsequently removed. As a result, the JSON feed (accessible at [this URL](https://api.nuget.org/v3-flatcontainer/sqlkata/index.json)) might still be reflecting outdated or incorrect information due to the caching mechanism used by NuGet.org.

When packages are uploaded and then removed, NuGet's cache may not immediately update to reflect these changes. This can lead to situations where references to non-existent versions persist in the feed, causing confusion or errors during package retrieval.

To resolve this, you may need to wait for the cache to expire and refresh, or contact NuGet support to expedite the process if the issue persists. 

![image](https://github.com/user-attachments/assets/bf133889-49f8-48e3-9be3-af5fe81d6b3d)

**Comment by askovpen** [comment]
this version (3.2.3) half year wrong

**Comment by askovpen** [comment]
https://github.com/NuGet/NuGetGallery/issues/10164

**Comment by askovpen** [comment]
https://github.com/NuGet/NuGetGallery/issues/10164#issuecomment-2315322282
